version: 0.2

phases:
  install:
    commands:
      # install node 16
      - echo Installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencing...
      - npm ci
      - npm i --save moment
  build:
    commands:
      - echo installing python requirements
      - pip install -r requirements.txt
      - echo Building...
      - npm run build
      - echo Testing...
      - CI=true npm test
artifacts:
  baseDirectory: build
  files:
    - '**/*'
  cache:
    paths:
      - node_modules/**/*