version: 0.2

phases:
  install:
    commands:
      # install node 16
      - echo Installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - echo Testing...
      - yarn test
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist