version: 0.2

phases:
  install:
    commands:
      # install node 16
      - echo Installing Node 16...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencing...
      - npm install
      - npm install react-router-dom@5.2.0
      - npm install axios
      - npm install react-moment
      - npm install @mui/material
      - npm install @mui/icons-material
  build:
    commands:
      - echo Testing...
      - npm test
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist