version: 0.2

phase:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
      - apt install -y nodejs
      - echo Installing app dependecies
      - npm ci
      - npm install moment
  build:
    commands:
      - echo Building static site...
      - npm build
      - echo Run tests...
      - CI=true npm test
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist

