# Generated by Django 3.2.9 on 2021-11-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('growth', models.FloatField()),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=150)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patients')),
            ],
        ),
    ]
