# Generated by Django 3.2.9 on 2021-11-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
