# Generated by Django 3.2.9 on 2021-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='first_name',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='last_name',
            new_name='title',
        ),
    ]
