# Generated by Django 3.2.9 on 2021-11-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211120_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='body',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='title',
            new_name='last_name',
        ),
    ]
