# Generated by Django 3.2.9 on 2021-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211120_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='growth',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='weight',
        ),
        migrations.AddField(
            model_name='patients',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patients',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
