# Generated by Django 3.2.9 on 2021-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211124_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
