# Generated by Django 3.2.9 on 2021-11-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comments_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
