# Generated by Django 3.2.9 on 2021-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211125_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
