# Generated by Django 3.2.9 on 2021-11-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patients_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
