# Generated by Django 3.2.9 on 2021-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patients_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
