# Generated by Django 3.2.9 on 2021-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patients_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
