# Generated by Django 3.2.9 on 2021-11-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_patients_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='year',
        ),
    ]
